version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db
    environment:
      # Variáveis de ambiente para o PostgreSQL
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ibge_pib_populacao
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl
    depends_on:
      - postgres
    environment:
      # Variáveis de ambiente para o ETL
      DB_NAME: ibge_pib_populacao
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py

volumes:
  pgdata: